# Título e informações do seu site
title: Vinícius Calgaro
author: Vinícius Calgaro
url: https://vinicalgaro.github.io/portfolio/ # URL raiz do seu site
description: > 
  Desenvolvedor Mobile Pleno e Especialista em Flutter & Android Nativo. Foco em Engenharia de Software, Arquitetura Limpa, Jetpack Compose e Soluções Híbridas Complexas.

# Configurações do tema Moonwalk
remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "auto" # "light", "dark" ou "auto"
  appearance_toggle: true
  back_home_text: "home"
  date_format: "%d/%m/%Y"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true

  # Títulos das seções
  home:
    title_projects: Projetos de Destaque
    title_blog: Blog

  # Opções de exibição
  show_projects: true
  show_blog: false 
  show_reading_time: true
  show_tags: true

# Plugins Jekyll
plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag